# Generated by Django 3.2 on 2023-10-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_student', models.CharField(max_length=80)),
                ('cell_phone', models.IntegerField()),
                ('email_field', models.EmailField(max_length=255)),
                ('faculty', models.CharField(max_length=100)),
                ('department_graduated_from', models.CharField(choices=[('department of computing and informatics', 'Department of Computing and Informatics'), ('department of journalism and communication', 'Department Of Journalism and Communication'), ('department of architecture', 'Department of Architecture')], max_length=255)),
                ('home_address', models.CharField(max_length=150)),
                ('motivation', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
