# Generated by Django 3.2 on 2023-10-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_event', models.CharField(max_length=255)),
                ('date_of_event', models.DateTimeField()),
                ('extra_info', models.TextField()),
                ('event_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
