# Generated by Django 3.2 on 2023-10-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnigallery',
            name='event_location',
            field=models.CharField(default='Unknown', max_length=250),
        ),
    ]
