# Generated by Django 3.2 on 2023-10-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryApp', '0002_alumnigallery_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnigallery',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=12),
        ),
    ]
