# Generated by Django 3.2 on 2023-10-28 00:42

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('galleryApp', '0003_alumnigallery_status'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='alumnigallery',
            managers=[
                ('publishedGallery', django.db.models.manager.Manager()),
            ],
        ),
    ]
