# Generated by Django 3.2 on 2023-10-28 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleryApp', '0004_alter_alumnigallery_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumnigallery',
            options={'ordering': ('-date_of_event',)},
        ),
    ]
