# Generated by Django 3.2 on 2023-10-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_organizer', models.CharField(max_length=255)),
                ('department', models.CharField(choices=[('department of software development', 'Department Of software Development'), ('department of civil engineering', 'Department Of Civil Engineering'), ('department of tourism', 'Department Of Tourism'), ('inclusive', 'Inclusive')], default='inclusive', max_length=300)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
