# Generated by Django 3.2 on 2023-10-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsApp', '0002_eventsapp_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsapp',
            name='department',
            field=models.CharField(choices=[('department of software development', 'Department Of software Development'), ('department of civil engineering', 'Department Of Civil Engineering'), ('department of tourism', 'Department Of Tourism'), ('inclusive', 'Inclusive')], max_length=300),
        ),
    ]
